CREATE TABLE beasiswa (
    id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    siswa_id BIGINT UNSIGNED NOT NULL,
    nama_beasiswa VARCHAR(150) NULL,
    tahun VARCHAR(10) NULL,
    keterangan TEXT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (siswa_id) REFERENCES siswa(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

