CREATE TABLE siswa (
    id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    uuid CHAR(36) NOT NULL UNIQUE,
    nik VARCHAR(20) NULL,
    nisn VARCHAR(20) NULL,
    kip VARCHAR(50) NULL,
    nama VARCHAR(150) NOT NULL,
    tempat_lahir VARCHAR(100) NULL,
    tanggal_lahir DATE NULL,
    jenis_kelamin ENUM('Laki-laki','Perempuan') NULL,
    agama VARCHAR(30) NULL,
    jumlah_saudara TINYINT UNSIGNED NULL,
    anak_ke TINYINT UNSIGNED NULL,
    hobi VARCHAR(100) NULL,
    cita_cita VARCHAR(100) NULL,
    no_handphone VARCHAR(20) NULL,
    email VARCHAR(100) NULL,
    yang_membiayai VARCHAR(50) NULL,
    kebutuhan_disabilitas VARCHAR(50) NULL,
    kebutuhan_khusus VARCHAR(50) NULL,
    alamat TEXT NULL,
    status_tempat_tinggal VARCHAR(50) NULL,
    jarak_rumah_madrasah VARCHAR(50) NULL,
    waktu_tempuh VARCHAR(30) NULL,
    transportasi VARCHAR(50) NULL,
    fingerprint VARCHAR(255) NULL,
    rfid VARCHAR(50) NULL,
    source ENUM('pendaftaran','emis_scraping','manual') NOT NULL DEFAULT 'manual',
    source_page INT NULL,
    source_row INT NULL,
    is_failed BOOLEAN NOT NULL DEFAULT FALSE,
    raw_json JSON NULL,
    deleted_at TIMESTAMP NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    INDEX idx_nik (nik),
    INDEX idx_nisn (nisn),
    INDEX idx_rfid (rfid),
    INDEX idx_nama (nama),
    INDEX idx_deleted_at (deleted_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
