CREATE TABLE scraper_configs (
    id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    scraper_name VARCHAR(100) NOT NULL UNIQUE,
    config_encrypted TEXT NOT NULL,
    updated_by VARCHAR(100) NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
